### PR TITLE
Checkpoint 7 upgrading

### PR DESCRIPTION
**Pull request by brooksmarka**
Marks-MacBook-Pro:wikicamp markbrooks$ rspec spec
..........................

Finished in 1.4 seconds (files took 3.65 seconds to load)
26 examples, 0 failures

Coverage report generated for RSpec to /Users/markbrooks/Programming/bloc/wikicamp/coverage. 325 / 359 LOC (90.53%) covered.

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@brooksmarka can you please post the test coverage % in the description above? 

I'd like to see this: 

Description: <short sentence as to what was built>
Test Coverage: % from Simplecov

**Comment by brooksmarka** [comment]
Hi Britt,

I just updated the comment.  I think that gave you an alert, but since I'm
not 100% positive I thought I would write you here as well.

Thanks,

Mark

**Comment by brittanyjspringer** [comment]
Thank you, @brooksmarka! ⭐️

**Comment by brittanyjspringer** [comment]
@brooksmarka please submit the checkpoint with a link to this PR. Thanks!

**Pull request merged**
